image: python:3.11-slim

stages:
  - build
  - security
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Executando etapa de Build..."
    - pip install -r requirements.txt
    - python -m compileall .

bandit_job:
  stage: security
  script:
  - pip install -r requirements.txt
  - echo "Executando analise estatica de seguranca com Bandit..."
  - bandit -r .

pip_audit_job:
  stage: secutity
  script:
  - pip install -r requirements.txt
  - echo "Verificando dependencias com pip-audit..."
  - pip-audit

test_job:
  stage: test
  script:
    - echo "Executando testes automatizados com unittest..."
    - python -m unittest discover -s tests -v

deploy_job:
  stage: deploy
  script:
    - echo "Deploy realizado com sucesso!"
